### ISSUE TITLE
Could not resolve to a ProjectV2 with the number 12.

### ISSUE THREAD

**Issue by WouterBos** [blombard/move-to-next-iteration#1]
Hi! I get this error message:

> Run blombard/move-to-next-iteration@master
> Error: Request failed due to following response errors:
>  - Could not resolve to a ProjectV2 with the number 12.

I got the number from this URL: [https://github.com/orgs/infinitaslearning/projects/**12**](https://github.com/orgs/infinitaslearning/projects/12)

This is yml i used:

```
name: Iteration transition

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  move-to-next-iteration:
    name: Move issues to next iteration
    runs-on: ubuntu-latest

    steps:
      - uses: blombard/move-to-next-iteration@master
        with:
          owner: infinitaslearning
          number: 12
          token: ${{ secrets.GITHUB_TOKEN }}
          iteration-field: Iteration
          iteration: last
          new-iteration: current
          statuses: 🔜 Todo, 👩‍💻 Coding, 👀 Ready for testing, 📒 Awaiting documentation
```

I guess I did something wrong in the configuration?
