### ISSUE TITLE
Cannot read properties of undefined (reading 'title')

### ISSUE THREAD

**Issue by stevebauman** [blombard/move-to-next-iteration#18]
First of all, thanks for this action! Appreciate your work here ❤️ 

We started getting this error a day ago:

```
Cannot read properties of undefined (reading 'title')
```

![Screenshot 2024-10-10 at 12 31 09 PM](https://github.com/user-attachments/assets/a920c09c-c8f0-4669-a1ee-90d18d9351fe)

Here's out action.yml:

```yml
name: move-to-next-iteration

on:
    schedule:
        -   cron: '0 5 * * *'
    workflow_dispatch:

jobs:
    move-to-next-iteration:
        name: Move to next iteration
        runs-on: ubuntu-latest

        steps:
            -   uses: blombard/move-to-next-iteration@v0.5.0
                with:
                    owner: repository
                    number: 22
                    token: ${{ secrets.PROJECT_MANAGEMENT_TOKEN }}
                    iteration-field: Iteration
                    iteration: last
                    new-iteration: current
                    excluded-statuses: "Done"
```

We tried downgrading to v0.5.0, but receive the same error.

Maybe GitHub changed something in their API?

Appreciate any help or assistance. Let me know if you need any more information!
