### ISSUE TITLE
Duplicate iteration names causes move to old iteration

### ISSUE THREAD

**Issue by StevenBosch1** [blombard/move-to-next-iteration#34]
I Just ran the workflow manually and all of the tickets disappeared. It turns out they were moved into last year's `sprint 8`, rather than the current `sprint 8`.

workflow yaml:

```
on:
  workflow_dispatch:

jobs:
  move-to-next-iteration:
    name: Move to next iteration
    runs-on: ubuntu-latest

    steps:
    - uses: blombard/move-to-next-iteration@master
      with:
        owner: OwnerName
        number: 4
        token: ${{ secrets.PAT }}
        iteration-field: sprint
        iteration: previous
        new-iteration: current
        excluded-statuses: "Done,Won't Fix"
```
