### ISSUE TITLE
Different weekly-sprint dates in the action

### ISSUE THREAD

**Issue by tty47** [blombard/move-to-next-iteration#7]
hello!

I'm facing issues when moving from the previous weekly sprint to the current one, it looks like the action has/detects different dates...

The first part is where the action moved the issues, and the second weekly sprint is the real current one:

![Screenshot 2024-01-29 at 07 27 50](https://github.com/blombard/move-to-next-iteration/assets/32740567/0bfe82d9-dd71-4f90-aa56-c5f4bf660bc2)

I have this config:
```yaml
name: Move To Next Iteration

on:
  workflow_dispatch:
  schedule:
    # Runs "at 05:00, only on Monday" (see https://crontab.guru)
    - cron: '0 5 * * 1'

jobs:
  move-to-next-iteration:
    name: Move to next iteration
    runs-on: ubuntu-latest

    steps:
    - uses: blombard/move-to-next-iteration@master
      with:
        owner: <project>
        number: <id>
        token: ${{ secrets.PROJECT_PAT }}
        iteration-field: "Weekly-Sprint"
        iteration: last
        new-iteration: current
        excluded-statuses: "Done"
```

is there something wrong?

thanks in advance!
