### ISSUE TITLE
Setup "Statuses" options doesn't limit the update to tickets having status from the list

### ISSUE THREAD

**Issue by msimon** [blombard/move-to-next-iteration#8]
I have the following configuration

```
jobs:
  move-to-next-sprint:
    name: Move to next Sprint
    runs-on: ubuntu-latest

    steps:
    - uses: blombard/move-to-next-iteration@master
      with:
        owner: HeroJourneyClub
        number: 2
        token: ${{ secrets.PROJECT_GITHUB_SECRET }}
        iteration-field: Sprint
        iteration: last
        new-iteration: current
        statuses: 'Eng Review'
 ```
 
 I simplified it as the bug is happening even with only one status. 
 
When I run the command, all the tickets from my past sprint are being move to the current one, not only the one that have the "Eng Review" status.

I'll take a quick look and see if I can send a PR soon if it's easy
